name: Scazmo Reposter

on:
  workflow_dispatch:

jobs:
  repost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scazmo reposter
        env:
          BSKY_USERNAME: scazmo.bsky.social
          BSKY_PASSWORD: ${{ secrets.SCAZMO_PASSWORD }}
        run: python scazmo_reposter.py
